apiVersion: v1
kind: Service
metadata:
  name: kubernetes-website-demo
  labels:
    app: website-demo

spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: tomcat
    port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: website-demo
    tier: web
