apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-website-demo
  labels:
    app: website-demo
    
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: website-demo
      tier: web
  template:
    metadata:
      labels:
        app: website-demo
        tier: web
    spec:
      containers:
      - name: static-website
        image: emestiza/websitedeploy
        ports:
        - containerPort: 8082
      
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
            
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
